root: true
env:
  browser: true
  es6: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  project: './tsconfig.json'
  sourceType: module
plugins:
  - react
  - import
  - unicorn
  - security
  - prettier
  - react-hooks
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:unicorn/recommended
  - plugin:security/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - prettier/unicorn
  - prettier/react
rules:
  prefer-const: error
  react/prop-types: 'off'
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  unicorn/prevent-abbreviations: 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-member-accessibility': 'off'
  '@typescript-eslint/consistent-type-definitions':
    - error
    - type
settings:
  react:
    version: detect
  import/resolver:
    babel-module: {}
  import/parsers:
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
