'package.json':
  - prettier-package-json --write
'*.tsx':
  - eslint --fix
'*.css':
  - stylelint --fix
'*.json':
  - prettier --write
'*.yml':
  - prettier --write
'*.md':
  - prettier --write
'*':
  - secretlint
