'package.json':
  - prettier-package-json --write
'*.{js,ts,tsx}':
  - eslint --fix
'*.{js,ts,tsx,css,scss}':
  - stylelint --fix
'*.json':
  - prettier --write
'*.yml':
  - prettier --write
'*.md':
  - prettier --write
'*':
  - secretlint
