version: 2.1
executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/node:11
        environment:
          LEFTHOOK: '0'
  browser:
    working_directory: ~/app
    docker:
      - image: circleci/node:11-browsers
        environment:
          LEFTHOOK: '0'
commands:
  restore-dependencies:
    steps:
      - restore_cache:
          keys:
            - app-deps-{{ checksum "yarn.lock" }}
            - app-deps
  save-dependencies:
    steps:
      - save_cache:
          key: app-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/app/node_modules
jobs:
  setup:
    executor: default
    steps:
      - checkout
      - restore-dependencies
      - run:
          name: Install dependencies
          command: yarn install
      - save-dependencies
  check-linter:
    executor: default
    steps:
      - checkout
      - restore-dependencies
      - run:
          name: Run lint
          command: yarn lint
  check-types:
    executor: default
    steps:
      - checkout
      - restore-dependencies
      - run:
          name: Run typecheck
          command: yarn typecheck
  run-integration-test:
    executor: browser
    steps:
      - checkout
      - restore-dependencies
      - run:
          name: Run integration test
          command: yarn test:integration
  dry-run-build:
    executor: default
    steps:
      - checkout
      - restore-dependencies
      - run:
          name: Run build
          command: yarn build
workflows:
  work:
    jobs:
      - setup
      - check-linter:
          requires:
            - setup
      - check-types:
          requires:
            - setup
      - run-integration-test:
          requires:
            - setup
      - dry-run-build:
          requires:
            - setup
            - check-linter
            - check-types
            - run-integration-test
