version: 2.1
executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/node:11
        environment:
          HUSKY_SKIP_INSTALL: true
  browser:
    working_directory: ~/app
    docker:
      - image: circleci/node:11-browsers
        environment:
          HUSKY_SKIP_INSTALL: true
commands:
  restore-dependencies:
    steps:
      - restore_cache:
          keys:
            - app-deps-{{ checksum "yarn.lock" }}
            - app-deps
  save-dependencies:
    steps:
      - save_cache:
          key: app-deps-{{ checksum "yarn.lock" }}
          paths: ~/app/node_modules
  persist-workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths: .
  attach-workspace:
    steps:
      - attach_workspace:
          at: .
jobs:
  setup:
    executor: default
    steps:
      - checkout
      - restore-dependencies
      - run:
          name: Install dependencies
          command: yarn install
      - save-dependencies
      - persist-workspace
  check-linter:
    executor: default
    steps:
      - attach-workspace
      - run:
          name: Run lint
          command: yarn lint
  check-types:
    executor: default
    steps:
      - attach-workspace
      - run:
          name: Run typecheck
          command: yarn typecheck
  run-e2e-test:
    executor: browser
    steps:
      - attach-workspace
      - run:
          name: Run integration test
          command: yarn test
  build:
    executor: default
    steps:
      - attach-workspace
      - run:
          name: Run build
          command: yarn build
workflows:
  work:
    jobs:
      - setup
      - check-linter:
          requires:
            - setup
      - check-types:
          requires:
            - setup
      - run-e2e-test:
          requires:
            - setup
      - build:
          requires:
            - setup
            - check-linter
            - check-types
            - run-e2e-test
