name: automerge-dependabot
on:
  pull_request_review:
    types:
      - submitted
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  merge:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: false
          labels: dependencies
          checks_enabled: true
          method: squash
