name: check-pull-request
on: pull_request
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@master
      - run: npm run lint
      - run: npm run typecheck
  build:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@master
      - run: npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}
  auto-approve:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
