on:
  pull_request:
    types: [synchronize, opened, reopened, closed]
env:
  CI: true
  TZ: Asia/Tokyo
  IDENTIFIER: ymkzco-pr-${{ github.event.number }}
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "vercel:  v`vercel --version`"
      - run: |
          echo "CI: ${CI}"
          echo "TZ: ${TZ}"
          echo "IDENTIFIER: ${IDENTIFIER}"
      - run: date
      - run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  check:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: cat package.json | jq .volta.node
      - uses: bahmutov/npm-install@master
      - run: yarn run lint:js
      - run: yarn run lint:css
      - run: yarn run typecheck
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize'
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: cat package.json | jq .volta.node
      - uses: bahmutov/npm-install@master
      - run: yarn run build
      - run: >
          vercel
          deploy
          --token ${{ secrets.ZEIT_TOKEN }}
          --no-clipboard
          --confirm
          > deployment-preview-url.txt
      - run: >
          vercel
          alias
          --token ${{ secrets.ZEIT_TOKEN }}
          `cat deployment-preview-url.txt`
          ${{ env.IDENTIFIER }}.now.sh
      - run: >
          curl
          -X POST
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          -d "{ \"body\": \"Ready to preview deploy\n- Preview: https://${{ env.IDENTIFIER }}.now.sh\" }"
          ${{ github.event.pull_request.comments_url }}
        if: github.event.action == 'opened'
  remove-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - run: >
          curl
          "https://api.zeit.co/v11/now/deployments/get?url=${{ env.IDENTIFIER }}.now.sh"
          -H "Authorization: Bearer ${{ secrets.ZEIT_TOKEN }}"
          | jq -r ".id"
          > deployment-preview-id.txt
      - run: >
          vercel
          remove
          --token ${{ secrets.ZEIT_TOKEN }}
          --yes
          `cat deployment-preview-id.txt`
