on:
  schedule:
    # every week Monday AM 10:00
    - cron: 00 10 * * 1
env:
  CI: true
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "now:  v`now --version`"
      - run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-
      - uses: actions/cache@v1
        id: build-cache
        with:
          path: .next
          key: build-${GITHUB_SHA}
          restore-keys: build-${GITHUB_SHA}
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        env:
          HUSKY_SKIP_INSTALL: 1
      - run: yarn run build
        if: steps.build-cache.outputs.cache-hit != 'true'
  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: build-cache
        with:
          path: .next
          key: build-${GITHUB_SHA}
          restore-keys: build-${GITHUB_SHA}
      - run: now --prod --no-clipboard --token $ZEIT_TOKEN
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
  lighthouse:
    runs-on: ubuntu-latest
    needs: deploy-production
    steps:
      - uses: actions/checkout@v1
      - uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://ymkz.co/
            https://ymkz.co/about
            https://ymkz.co/contact
            https://ymkz.co/projects
      - uses: actions/upload-artifact@v1
        with:
          name: lighthouse-artifact
          path: .lighthouseci
