on:
  schedule:
    # At 00:00 on Monday and Thursday
    - cron: 0 0 * * 1,4
env:
  CI: true
  TZ: Asia/Tokyo
  CACHE: cache-0.0.0
  HUSKY_SKIP_INSTALL: 1
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "now:  v`now --version`"
      - run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: $CACHE-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: $CACHE-yarn-
      - uses: actions/cache@v1
        id: build-cache
        with:
          path: .next
          key: $CACHE-build-$GITHUB_SHA
          restore-keys: $CACHE-build-$GITHUB_SHA
      - run: yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn run build
        if: steps.build-cache.outputs.cache-hit != 'true'
  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: build-cache
        with:
          path: .next
          key: $CACHE-build-$GITHUB_SHA
          restore-keys: $CACHE-build-$GITHUB_SHA
      - run: >
          now
          --token $ZEIT_TOKEN
          --no-clipboard
          --prod
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
