on:
  schedule:
    - cron: 0 0 * * 1,3,5
    # At 00:00 on Monday, Wednesday and Friday
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "now:  v`now --version`"
      - run: |
          echo "CI: ${CI}"
          echo "TZ: ${TZ}"
      - run: date
      - run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=version::$(cat .node-version)"
        id: node-version
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - uses: bahmutov/npm-install@v1
      - run: yarn run build
      - run: >
          now
          deploy
          --token $ZEIT_TOKEN
          --no-clipboard
          --confirm
          --prod
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
