on:
  schedule:
    - cron: 0 0 * * 0 # Run at Sunday
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "vercel:  v`vercel --version`"
      - run: |
          echo "CI: ${CI}"
          echo "TZ: ${TZ}"
      - run: date
      - run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@master
      - run: yarn run build
      - run: >
          vercel
          deploy
          --token $ZEIT_TOKEN
          --no-clipboard
          --confirm
          --prod
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
