on:
  schedule:
    - cron: '0 9,21 * * *' # Run this every day at 9am and 21pm
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "now:  v`now --version`"
      - run: |
          echo "CI: ${CI}"
          echo "TZ: ${TZ}"
          echo "IDENTIFIER: ${IDENTIFIER}"
      - run: date
      - run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  github-notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SeanReece/pr-reporter-slack@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
