on:
  schedule:
    - cron: '0 9,11 * * *' # Run this every day at 9am and 1pm
jobs:
  github-notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: SeanReece/pr-reporter-slack@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
