on:
  schedule:
    - cron: 0 0 * * 1 # At 00:00 on Monday
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "now:  v`now --version`"
      - run: |
          echo "CI: ${CI}"
          echo "TZ: ${TZ}"
          echo "IDENTIFIER: ${IDENTIFIER}"
      - run: date
      - run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'https://ymkz.co'
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK }}
