name: pullrequest
on: pull_request
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm run codecheck
      - run: npm run build
