name: pullrequest
on: pull_request
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}
  automerge:
    runs-on: ubuntu-latest
    needs:
      - check
      - build
    steps:
      - uses: ridedott/merge-me-action@v1.8.117
        if: github.actor == 'dependabot[bot]'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_LOGIN: dependabot[bot]
          PRESET: DEPENDABOT_MINOR
