name: remove-stale-deployment
on:
  schedule:
    - cron: 0 0 * * 0
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - run: vercel remove ymkz.co --safe --yes --token ${{ secrets.VERCEL_TOKEN }}
