on:
  push:
    branches:
      - master
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "node: `node --version`"
          echo "npm:  v`npm --version`"
          echo "yarn: v`yarn --version`"
          echo "now:  v`now --version`"
      - run: date
      - run: echo "${{ toJson(github) }}"
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=version::$(cat .node-version)"
        id: node-version
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node-version.outputs.version }}
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run typecheck
